/**
 * Example: Simulate depth curves for a Hadron pool.
 *
 * Reads pool configuration from output/pool-config.json (generated by test 01),
 * recreates the pool in LiteSVM at various inventory levels, executes swaps,
 * and generates an HTML visualization with an interactive slider.
 *
 * The depth chart shows effective price vs cumulative volume.
 * The risk chart shows bid/ask spread (bps) vs inventory %.
 *
 * Run:
 *   npm test
 *
 * Output:
 *   output/depth-curves.html
 */
import { describe, it } from "vitest";
import { LiteSVM, FeatureSet } from "litesvm";
import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  TransactionInstruction,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  MintLayout,
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  createMintToInstruction,
} from "@solana/spl-token";
import {
  Hadron,
  toQ32,
  Interpolation,
  Side,
  getFeeConfigAddress,
  decodeFeeConfig,
  decodeConfig,
  decodeMidpriceOracle,
  decodeCurveMeta,
  derivePoolAddresses,
  HADRON_PROGRAM_ID,
} from "@hadron-fi/sdk";
import fs from "fs";
import path from "path";
import { logHeader, logInfo, PROGRAM_ID } from "../setup";
import {
  type PoolConfig,
  type AnimationFrame,
  type RiskPoint,
  DEFAULT_CONFIG,
  generateDepthHtml,
} from "../generate-depth-html";

// ============================================================================
// LiteSVM helpers
// ============================================================================

const PROGRAM_PATH = path.resolve(__dirname, "../../programs/hadron.so");

function humanToAtoms(amount: number, decimals: number): bigint {
  return BigInt(Math.round(amount * 10 ** decimals));
}

function atomsToHuman(atoms: bigint, decimals: number): number {
  return Number(atoms) / 10 ** decimals;
}

function getTokenBalance(svm: LiteSVM, ata: PublicKey): bigint {
  const account = svm.getAccount(ata);
  if (!account) return 0n;
  const data = Buffer.from(account.data);
  return data.readBigUInt64LE(64);
}

function sendTx(
  svm: LiteSVM,
  payer: Keypair,
  ixs: TransactionInstruction[],
  signers?: Keypair[]
): void {
  const tx = new Transaction();
  for (const ix of ixs) tx.add(ix);
  tx.feePayer = payer.publicKey;
  tx.recentBlockhash = svm.latestBlockhash();
  tx.sign(payer, ...(signers ?? []));
  const result = svm.sendTransaction(tx);
  if (typeof (result as any).err === "function") {
    const logs =
      typeof (result as any).meta === "function"
        ? (result as any).meta().logs()
        : [];
    throw new Error(
      `Transaction failed: ${(result as any).toString()}\nLogs: ${logs.join("\n")}`
    );
  }
  svm.expireBlockhash();
}

function createMintInSvm(
  svm: LiteSVM,
  payer: Keypair,
  mintKp: Keypair,
  decimals: number
): void {
  const data = Buffer.alloc(MintLayout.span);
  MintLayout.encode(
    {
      mintAuthorityOption: 1,
      mintAuthority: payer.publicKey,
      supply: 0n,
      decimals,
      isInitialized: true,
      freezeAuthorityOption: 0,
      freezeAuthority: PublicKey.default,
    },
    data
  );
  svm.setAccount(mintKp.publicKey, {
    lamports: 1_000_000_000n,
    data,
    owner: TOKEN_PROGRAM_ID,
    executable: false,
  });
}

function createAtaIfNeeded(
  svm: LiteSVM,
  payer: Keypair,
  owner: PublicKey,
  mint: PublicKey
): PublicKey {
  const ata = getAssociatedTokenAddressSync(mint, owner, true);
  if (svm.getAccount(ata)) return ata;
  const ix = createAssociatedTokenAccountInstruction(
    payer.publicKey,
    ata,
    owner,
    mint
  );
  sendTx(svm, payer, [ix]);
  return ata;
}

function loadPoolFromSvm(svm: LiteSVM, poolAddress: PublicKey): Hadron {
  const configData = svm.getAccount(poolAddress);
  if (!configData)
    throw new Error(`Pool not found: ${poolAddress.toBase58()}`);
  const config = decodeConfig(new Uint8Array(configData.data));
  const addrs = derivePoolAddresses(
    config.seed,
    config.mintX,
    config.mintY,
    config.tokenProgramX,
    config.tokenProgramY,
    HADRON_PROGRAM_ID
  );
  const oracleData = svm.getAccount(addrs.midpriceOracle);
  if (!oracleData) throw new Error("Oracle not found");
  const curveMetaData = svm.getAccount(addrs.curveMeta);
  if (!curveMetaData) throw new Error("CurveMeta not found");
  const curvePrefabsData = svm.getAccount(addrs.curvePrefabs);
  if (!curvePrefabsData) throw new Error("CurvePrefabs not found");
  return new Hadron(
    null as any,
    poolAddress,
    addrs,
    config,
    decodeMidpriceOracle(new Uint8Array(oracleData.data)),
    decodeCurveMeta(new Uint8Array(curveMetaData.data)),
    new Uint8Array(curvePrefabsData.data),
    HADRON_PROGRAM_ID
  );
}

// ============================================================================
// Pool creation + swap simulation
// ============================================================================

let seedCounter = 0n;

function simulateSwap(
  svm: LiteSVM,
  payer: Keypair,
  mintX: PublicKey,
  mintY: PublicKey,
  payerAtaX: PublicKey,
  payerAtaY: PublicKey,
  feeRecipient: PublicKey,
  config: PoolConfig,
  pctBase: number,
  direction: "bid" | "ask",
  volumeHuman: number
): { amountIn: bigint; amountOut: bigint } | null {
  try {
    seedCounter++;

    // 1. Initialize pool
    const { instructions, poolAddress } = Hadron.initialize(payer.publicKey, {
      seed: seedCounter,
      mintX,
      mintY,
      authority: payer.publicKey,
      initialMidpriceQ32: toQ32(config.midprice),
    });
    sendTx(svm, payer, instructions);

    // 2. Load pool from SVM state
    const pool = loadPoolFromSvm(svm, poolAddress);

    // 3. Set price curves
    sendTx(svm, payer, [
      pool.setCurve(payer.publicKey, {
        side: Side.Bid,
        defaultInterpolation: Interpolation.Linear,
        slot: 0,
        points: config.priceCurves.bid.points.map((p) => ({
          amountIn: humanToAtoms(p.volume, config.decimalsX),
          priceFactor: p.priceFactor,
        })),
      }),
      pool.setCurve(payer.publicKey, {
        side: Side.Ask,
        defaultInterpolation: Interpolation.Linear,
        slot: 0,
        points: config.priceCurves.ask.points.map((p) => ({
          amountIn: humanToAtoms(p.volume, config.decimalsY),
          priceFactor: p.priceFactor,
        })),
      }),
    ]);

    // 4. Set risk curves
    sendTx(svm, payer, [
      pool.setRiskCurve(payer.publicKey, {
        side: Side.Bid,
        defaultInterpolation: Interpolation.Linear,
        slot: 0,
        points: config.riskCurves.bid.points,
      }),
      pool.setRiskCurve(payer.publicKey, {
        side: Side.Ask,
        defaultInterpolation: Interpolation.Linear,
        slot: 0,
        points: config.riskCurves.ask.points,
      }),
    ]);

    // 5. Create vault ATAs + deposit
    createAtaIfNeeded(svm, payer, pool.addresses.config, mintX);
    createAtaIfNeeded(svm, payer, pool.addresses.config, mintY);

    const baseValueUsd = config.totalValueUsd * pctBase;
    const quoteValueUsd = config.totalValueUsd * (1 - pctBase);
    const baseAmount = humanToAtoms(
      baseValueUsd / config.midprice,
      config.decimalsX
    );
    const quoteAmount = humanToAtoms(quoteValueUsd, config.decimalsY);

    sendTx(svm, payer, [
      pool.deposit(payer.publicKey, {
        amountX: baseAmount,
        amountY: quoteAmount,
      }),
    ]);

    // 6. Swap
    const inputDecimals =
      direction === "bid" ? config.decimalsX : config.decimalsY;
    const amountIn = humanToAtoms(volumeHuman, inputDecimals);
    const outputAta = direction === "bid" ? payerAtaY : payerAtaX;
    const beforeBalance = getTokenBalance(svm, outputAta);

    sendTx(svm, payer, [
      pool.swap(payer.publicKey, {
        isX: direction === "bid",
        amountIn,
        minOut: 0n,
        feeRecipient,
      }),
    ]);

    const afterBalance = getTokenBalance(svm, outputAta);
    const amountOut = afterBalance - beforeBalance;

    return { amountIn, amountOut };
  } catch {
    return null;
  }
}

// ============================================================================
// Data collection
// ============================================================================

function collectFrames(
  svm: LiteSVM,
  payer: Keypair,
  mintX: PublicKey,
  mintY: PublicKey,
  payerAtaX: PublicKey,
  payerAtaY: PublicKey,
  feeRecipient: PublicKey,
  config: PoolConfig,
  inventorySteps: number,
  probePointsPerSide: number,
  probeVolumeMax: number
): AnimationFrame[] {
  const frames: AnimationFrame[] = [];

  for (let step = 0; step < inventorySteps; step++) {
    const pctBase = 0.05 + (0.9 * step) / (inventorySteps - 1);
    process.stdout.write(
      `\x1b[33m  Frame ${step + 1}/${inventorySteps}\x1b[0m (${(pctBase * 100).toFixed(0)}% base) ... `
    );

    const bid: { price: number; cumVolume: number }[] = [];
    const ask: { price: number; cumVolume: number }[] = [];

    // Bid probes: sell X for Y
    for (let p = 1; p <= probePointsPerSide; p++) {
      const volume = (probeVolumeMax * p) / probePointsPerSide;
      const result = simulateSwap(
        svm, payer, mintX, mintY, payerAtaX, payerAtaY,
        feeRecipient, config, pctBase, "bid", volume
      );
      if (result && result.amountOut > 0n) {
        const inH = atomsToHuman(result.amountIn, config.decimalsX);
        const outH = atomsToHuman(result.amountOut, config.decimalsY);
        if (inH > 0 && outH > 0) bid.push({ price: outH / inH, cumVolume: inH });
      }
    }

    // Ask probes: sell Y for X (volume in quote tokens)
    for (let p = 1; p <= probePointsPerSide; p++) {
      const volumeBase = (probeVolumeMax * p) / probePointsPerSide;
      const volumeQuote = volumeBase * config.midprice;
      const result = simulateSwap(
        svm, payer, mintX, mintY, payerAtaX, payerAtaY,
        feeRecipient, config, pctBase, "ask", volumeQuote
      );
      if (result && result.amountOut > 0n) {
        const inH = atomsToHuman(result.amountIn, config.decimalsY);
        const outH = atomsToHuman(result.amountOut, config.decimalsX);
        if (inH > 0 && outH > 0) ask.push({ price: inH / outH, cumVolume: outH });
      }
    }

    frames.push({ pctBase, bid, ask });
    process.stdout.write(
      `\x1b[32mbid ${bid.length} pts, ask ${ask.length} pts\x1b[0m\n`
    );
  }

  return frames;
}

function collectRiskData(
  svm: LiteSVM,
  payer: Keypair,
  mintX: PublicKey,
  mintY: PublicKey,
  payerAtaX: PublicKey,
  payerAtaY: PublicKey,
  feeRecipient: PublicKey,
  config: PoolConfig,
  pctBaseValues: number[]
): RiskPoint[] {
  const testSizeBase = 1; // 1 token
  const results: RiskPoint[] = [];

  for (const pctBase of pctBaseValues) {
    const bidResult = simulateSwap(
      svm, payer, mintX, mintY, payerAtaX, payerAtaY,
      feeRecipient, config, pctBase, "bid", testSizeBase
    );
    const askResult = simulateSwap(
      svm, payer, mintX, mintY, payerAtaX, payerAtaY,
      feeRecipient, config, pctBase, "ask", testSizeBase * config.midprice
    );

    const bidPrice =
      bidResult && bidResult.amountOut > 0n
        ? atomsToHuman(bidResult.amountOut, config.decimalsY) /
          atomsToHuman(bidResult.amountIn, config.decimalsX)
        : null;
    const askPrice =
      askResult && askResult.amountOut > 0n
        ? atomsToHuman(askResult.amountIn, config.decimalsY) /
          atomsToHuman(askResult.amountOut, config.decimalsX)
        : null;

    results.push({ pctBase, bidPrice, askPrice });
  }
  return results;
}

// ============================================================================
// Test
// ============================================================================

describe("Simulate depth curves", () => {
  it("generates depth visualization from pool config", async () => {
    const config: PoolConfig = DEFAULT_CONFIG;

    logHeader("Setting up LiteSVM");

    // ---------------------------------------------------------------
    // LiteSVM setup
    // ---------------------------------------------------------------
    const svm = LiteSVM.default()
      .withFeatureSet(FeatureSet.allEnabled())
      .withSigverify(false)
      .withBuiltins()
      .withSysvars()
      .withDefaultPrograms()
      .withLamports(1_000_000_000_000_000n);

    svm.addProgramFromFile(PROGRAM_ID, PROGRAM_PATH);

    const payer = Keypair.generate();
    svm.airdrop(payer.publicKey, 100_000_000_000_000n);

    // Create token mints
    const mintX = Keypair.generate();
    const mintY = Keypair.generate();
    createMintInSvm(svm, payer, mintX, config.decimalsX);
    createMintInSvm(svm, payer, mintY, config.decimalsY);

    // Pull fee config from devnet and inject into LiteSVM
    const [feeConfigPda] = getFeeConfigAddress();
    const rpcUrl = process.env.RPC_URL || "https://api.devnet.solana.com";
    const devnetConn = new Connection(rpcUrl, "confirmed");
    const feeConfigAcct = await devnetConn.getAccountInfo(feeConfigPda);
    if (!feeConfigAcct) throw new Error("Fee config not found on devnet");

    svm.setAccount(feeConfigPda, {
      lamports: BigInt(feeConfigAcct.lamports),
      data: Buffer.from(feeConfigAcct.data),
      owner: HADRON_PROGRAM_ID,
      executable: false,
    });

    const feeConfig = decodeFeeConfig(feeConfigAcct.data);
    const feeRecipient = feeConfig.feeRecipient;
    svm.airdrop(feeRecipient, 1_000_000_000n);

    // Create ATAs for fee recipient and payer
    createAtaIfNeeded(svm, payer, feeRecipient, mintX.publicKey);
    createAtaIfNeeded(svm, payer, feeRecipient, mintY.publicKey);
    const payerAtaX = createAtaIfNeeded(svm, payer, payer.publicKey, mintX.publicKey);
    const payerAtaY = createAtaIfNeeded(svm, payer, payer.publicKey, mintY.publicKey);

    // Mint a large supply for the payer (covers all deposits + swaps)
    sendTx(svm, payer, [
      createMintToInstruction(mintX.publicKey, payerAtaX, payer.publicKey, BigInt("1000000000000000000")),
      createMintToInstruction(mintY.publicKey, payerAtaY, payer.publicKey, BigInt("1000000000000000000")),
    ]);

    // ---------------------------------------------------------------
    // Simulation parameters
    // ---------------------------------------------------------------
    const inventorySteps = 21;
    const probePointsPerSide = 25;
    const probeVolumeMax = 900; // max volume in base tokens

    logHeader("Collecting depth frames");
    logInfo(
      "Config:",
      `${inventorySteps} inventory levels, ${probePointsPerSide} probes/side, volume 0-${probeVolumeMax}`
    );

    const frames = collectFrames(
      svm, payer, mintX.publicKey, mintY.publicKey,
      payerAtaX, payerAtaY, feeRecipient,
      config, inventorySteps, probePointsPerSide, probeVolumeMax
    );

    logHeader("Collecting risk curve data");
    const riskData = collectRiskData(
      svm, payer, mintX.publicKey, mintY.publicKey,
      payerAtaX, payerAtaY, feeRecipient,
      config, frames.map((f) => f.pctBase)
    );

    // ---------------------------------------------------------------
    // Generate HTML
    // ---------------------------------------------------------------
    const outputDir = path.resolve(__dirname, "../../output");
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
    const htmlPath = path.join(outputDir, "depth-curves.html");
    generateDepthHtml(frames, riskData, config, htmlPath);

    logHeader("Done!");
    logInfo("Visualization:", htmlPath);
  }, 300_000); // 5 min timeout for simulation
});
